### ISSUE TITLE
Graph to notebook conversion

### ISSUE THREAD

**Issue by MathisFederico** [MathisFederico/OpenCodeBlocks#65]
We should be able to:
- convert .ipynb to linear graphs in .ipyg
- convert .ipyg to .ipynb in a reversible way with branding included

**Comment by FabienRoger** [comment]
I can help for this part "convert .ipynb to linear graphs in .ipyg" if you have not already done it (I have already looked into this).

**Comment by FabienRoger** [comment]
I see you have done a "Markdown block". I think this is a useful feature however I don't feel it's the right way to go for converting form ipynb to ipyg: I feel the markdown often don't belong between pieces of codes, but above them, where the "Title" is, but bigger, because markdown is most of the time an explanation for the piece of code just below it.
Maybe markdown blocks could be useful here only when there is >= 2 blocks of markdown in a row ?

**Comment by FabienRoger** [comment]
I think it would also be useful to have a function to merge code blocks: with ipyg blocks, it seems to me that one doesn't want small blocks (<= 4 lines) in the same way it is often done in jupyter notebooks (because 4 lines + 4 lines on top of each other is concise, but from left to right it is too much).
If you agree, add it as a distinct issue.

**Comment by vanyle** [comment]
For the markdown thing, because they are blocks, they can be moved anywhere around the code so you can have the markdown block just above your code.
When importing the pynb file, we could maybe set the splitter of the markdown so that only the rendered part of the markdown is displayed and so that the markdown overlaps with the title of the code cell ?

Merging block is a planned feature, work will need to be done, you can add it as an issue.
